kind: pipeline
name: default

steps:
- name: install
  image: johnpapa/angular-cli
  commands:
    - npm install

- name: test
  image: johnpapa/angular-cli
  commands:
    - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
