kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
  - npm install
  - npm install -g @angular/cli

steps:
- name: install
  image: trion/ng-cli
  commands:
  - ng serve --port 8080