kind: pipeline
name: default

steps:
- name: install
  image: johnpapa/angular-cli
  commands:
    - npm install

- name: test
  image: trion/ng-cli-karma:6.2.1
  commands:
    - ng test --progress false --watch false

- name: build
  image: johnpapa/angular-cli
  commands:
    - ng build --prod

- name: publish  
  image: plugins/gh-pages
  settings:
    username: miwtoo
    password: AAAAB3NzaC1yc2EAAAADAQABAAABAQDN64LS/cZ49zS+XZCt2JOWiPnT5kCMBGgGLtxfrMfHZiW/BxXB0rnB7Ejb8cbyJxdi+hAyIOb9xYvlcd7Za1mb5TbNF6wI4G6oVoEVJi0ql4tInDKKrNi4Z5tYwNJpnJrQ5XuCv6YsSiUHM1ytmSzmPc8PFdWijOnDRWBDT4gqRxzkOpWEx/Xek7067/mcVS7XKil99b8APyfrwGBq77w0m0FZijITmwqZ885SejZcIYFOpaQ3BYsJfI04g1NhPbuttEDdc0nToQLgOC8lEaIllmUWf2XKNYHwABGxIvlTO8Z9mj31A7PpRN9FqrRCt7iLtMTzhjv/Rxvcqa0pKNEn
    pages_directory: dist/drone-angular-git-test