kind: pipeline
name: default

steps:
- name: install
  image: johnpapa/angular-cli
  commands:
    - npm install

- name: test
  image: trion/ng-cli-karma:6.2.1
  commands:
    - ng test --progress false --watch false

- name: build
  image: johnpapa/angular-cli
  commands:
    - ng build --prod

- name: publish  
  image: plugins/gh-pages
  settings:
    username: miwtoo
    password: 0c9f6312a0637621542a4a18bdc68b88cc150646
    pages_directory: dist/drone-angular-git-test